#!/usr/bin/env bash
docker run --rm -ti \
    --user $(id -u):$(id -g) \
    --volume /etc/passwd:/etc/passwd:ro \
    --volume /etc/group:/etc/group:ro \
    --volume ~/.config/composer:/tmp \
    --volume $(pwd):/app \
    -w /app \
    infraspeak-pie/composer-parser-service-composer \
    composer $@
